version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: vuln_app
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MYSQL_DSN=root:${DB_PASSWORD}@tcp(db:3306)/vuln_app?parseTime=true&multiStatements=true&charset=utf8mb4
      - ALLOWED_ORIGINS=https://twitter-clone-app-56dhic2m.devinapps.com
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
    driver: local
