services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vuln_app
      MYSQL_USER: vuln_user
      MYSQL_PASSWORD: vuln_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: vuln_user
      DB_PASSWORD: vuln_pass
      DB_NAME: vuln_app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
