id: vuln-sns-general-cors-misconfiguration

info:
  name: vuln-sns General CORS Misconfiguration
  author: devin
  severity: medium
  description: CORS policy testing across all endpoints
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N
    cvss-score: 5.4
    cwe-id: CWE-346
  metadata:
    max-request: 3
  tags: cors,misconfiguration,general,vuln-sns

http:
  - method: OPTIONS
    path:
      - "{{BaseURL}}/api/posts"
    
    headers:
      Origin: "http://malicious-site.com"
      Access-Control-Request-Method: "POST"
      Access-Control-Request-Headers: "Content-Type,Authorization"
    
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Access-Control-Allow-Origin"
        part: header
      
      - type: status
        status:
          - 200
          - 204

  - method: GET
    path:
      - "{{BaseURL}}/api/health"
    
    headers:
      Origin: "http://evil.com"
    
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "*"
          - "http://evil.com"
        condition: or
        part: header
      
      - type: status
        status:
          - 200

  - method: POST
    path:
      - "{{BaseURL}}/api/login"
    
    headers:
      Content-Type: application/json
      Origin: "http://attacker.com"
    
    body: |
      {
        "user_id": "test",
        "password": "test"
      }
    
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Access-Control-Allow-Origin"
        part: header
      
      - type: status
        status:
          - 200
          - 401
